<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsUraPlugin>true</IsUraPlugin>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2026.07.02</Version>

    <PluginInternalName>RamenScenarioAnalyzer</PluginInternalName>
    <PluginDisplayName>RamenScenarioAnalyzer</PluginDisplayName>
    <PluginAuthor>UmamusumeResponseAnalyzer</PluginAuthor>
    <PluginDescription>解析拉面杯回合训练信息</PluginDescription>
    <PluginTargets>Cygames</PluginTargets>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RamenScenarioAnalyzerSmoke" />
    <Compile Remove="tests\**\*.cs" />
  </ItemGroup>

</Project>
